version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19

    commands:
      - dotnet-install.sh --jsonfile global.json
      - pip install cfn-lint

  build:
    commands:
      - dotnet publish -c Release
      - dotnet test -c Release

      - aws cloudformation package
        --template-file deploy/cfn-monitoring.template.yml
        --s3-bucket $ARTIFACT_STORE
        --output-template-file deploy/cfn-monitoring.template.yml.packaged

      - cfn-lint deploy/cfn-monitoring.template.yml.packaged
      - ./deploy/create-config-files.sh
artifacts:
  discard-paths: yes
  files:
    - "deploy/cfn-monitoring.template.yml.packaged"
    - "cfn-monitoring.*.config.json"
