version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 3.1
    commands:
      - pip install cfn-lint

  build:
    commands:
      - dotnet publish -c Release
      - dotnet test -c Release

      - aws cloudformation package
        --template-file deploy/master.template.yml
        --s3-bucket $ARTIFACT_STORE
        --output-template-file deploy/master.template.yml.packaged

      - aws cloudformation package
        --template-file deploy/agent.template.yml
        --s3-bucket $ARTIFACT_STORE
        --output-template-file deploy/agent.template.yml.packaged

      - cfn-lint deploy/master.template.yml.packaged
      - cfn-lint deploy/agent.template.yml.packaged

artifacts:
  discard-paths: yes
  files:
    - "deploy/master.template.yml.packaged"
    - "deploy/agent.template.yml.packaged"
