Transform: AWS::Serverless-2016-10-31
Parameters:
  CreateCrossAccountServiceRole:
    Type: String
    Description: Whether or not to create the cross account CloudWatch service role.
    AllowedValues:
      - "true"
      - "false"

  CreateSharingRole:
    Type: String
    Description: Whether or not to create the CloudWatch sharing role.
    AllowedValues:
      - "true"
      - "false"

  EnableServiceStopper:
    Type: String
    Description: Whether or not to create and enable the service stopper.
    AllowedValues:
      - "true"
      - "false"

  EnableCrossAccountEvents:
    Type: String
    Description: Whether or not to allow events published from the main account.
    AllowedValues:
      - "true"
      - "false"

  EnableCloudTrail:
    Type: String
    Description: Whether or not to enable CloudTrail logging.
    AllowedValues:
      - "true"
      - "false"

Conditions:
  CreateCrossAccountServiceRole: !Equals
    - !Ref CreateCrossAccountServiceRole
    - "true"

  CreateSharingRole: !Equals
    - !Ref CreateSharingRole
    - "true"

  EnableServiceStopper: !Equals
    - !Ref EnableServiceStopper
    - "true"

  EnableCrossAccountEvents: !Equals
    - !Ref EnableCrossAccountEvents
    - "true"

  EnableCloudTrail: !Equals
    - !Ref EnableCloudTrail
    - "true"

  CreateDeploymentsMetric: !And
    - !Equals
      - !Ref EnableCloudTrail
      - "true"
    - !Equals
      - !Ref EnableServiceStopper
      - "true"
Resources:
  ServiceLinkedRole:
    Type: AWS::IAM::ServiceLinkedRole
    Condition: CreateCrossAccountServiceRole
    Properties:
      AWSServiceName: cloudwatch-crossaccount.amazonaws.com
      Description: Allows CloudWatch to assume CloudWatch-CrossAccountSharing roles in remote accounts on behalf of the current account in order to display data cross-account, cross region

  SharingRole:
    Type: AWS::IAM::Role
    Condition: CreateSharingRole
    Properties:
      RoleName: CloudWatch-CrossAccountSharingRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              AWS: !ImportValue cfn-utilities:MasterAccountId
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchAutomaticDashboardsAccess
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
        - arn:aws:iam::aws:policy/AWSXrayReadOnlyAccess

  EventsPolicy:
    Type: AWS::Events::EventBusPolicy
    Condition: EnableCrossAccountEvents
    Properties:
      Principal: !ImportValue cfn-utilities:MasterAccountId
      Action: events:PutEvents
      StatementId: MasterAccountEvents

  ClustersWithStoppableServices:
    Type: AWS::ResourceGroups::Group
    Condition: EnableServiceStopper
    Properties:
      Name: ClustersWithStoppableServices
      Description: Clusters who have automatic service stopping enabled
      ResourceQuery:
        Type: TAG_FILTERS_1_0
        Query:
          ResourceTypeFilters: [AWS::ECS::Cluster]
          TagFilters:
            - Key: ENABLE_SERVICE_STOPPING
              Values: ["true"]

  ServiceStopperPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: EnableServiceStopper
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - resource-groups:ListGroupResources
              - tag:GetResources
              - ecs:ListServices
              - ecs:DescribeServices
              - ecs:UpdateService
            Resource: "*"

  ServiceStopper:
    Type: AWS::Serverless::Function
    Condition: EnableServiceStopper
    Properties:
      Runtime: dotnetcore3.1
      Handler: ServiceStopper::Cythral.CloudFormation.Monitoring.ServiceStopper.Handler::Handle
      CodeUri: ../bin/ServiceStopper/Release/netcoreapp3.1/publish/
      Timeout: 300
      Policies:
        - !Ref ServiceStopperPolicy
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
            Input: !Sub |
              {
                "MonitoredClustersGroupName": "${ClustersWithStoppableServices}"
              }

  CloudTrailBucket:
    Type: AWS::S3::Bucket
    Condition: EnableCloudTrail
    Properties:
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 30

  CloudTrailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: EnableCloudTrail
    Properties:
      Bucket: !Ref CloudTrailBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: s3:*
            Resource:
              - !Sub arn:aws:s3:::${CloudTrailBucket}
              - !Sub arn:aws:s3:::${CloudTrailBucket}/*
            Principal:
              Service: cloudtrail.amazonaws.com

  CloudTrailLogGroup:
    Type: AWS::Logs::LogGroup
    Condition: EnableCloudTrail
    Properties:
      RetentionInDays: 14

  CloudTrailRole:
    Type: AWS::IAM::Role
    Condition: EnableCloudTrail
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: cloudtrail.amazonaws.com
      ManagedPolicyArns:
        - !Ref CloudTrailPolicy

  CloudTrailPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: EnableCloudTrail
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: logs:*
            Resource: !GetAtt CloudTrailLogGroup.Arn

  CloudTrail:
    Type: AWS::CloudTrail::Trail
    Condition: EnableCloudTrail
    DependsOn:
      - CloudTrailBucketPolicy
    Properties:
      CloudWatchLogsLogGroupArn: !GetAtt CloudTrailLogGroup.Arn
      CloudWatchLogsRoleArn: !GetAtt CloudTrailRole.Arn
      S3BucketName: !Ref CloudTrailBucket
      IsLogging: true

  DeploymentsMetric:
    Type: AWS::Logs::MetricFilter
    Condition: CreateDeploymentsMetric
    Properties:
      FilterPattern: < { $.eventName = "UpdateStack" && $.userIdentity.invokedBy = "codepipeline.amazonaws.com" }
      LogGroupName: !Ref CloudTrailLogGroup
      MetricTransformations:
        - MetricName: Deployments
          MetricNamespace: Cythral/Monitoring
          MetricValue: 1
          DefaultValue: 0
