CloudTrailBucket:
  Type: AWS::S3::Bucket
  Properties:
    LifecycleConfiguration:
      Rules:
        - Status: Enabled
          ExpirationInDays: 30

CloudTrailBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: Ref: CloudTrailBucket
    PolicyDocument:
      Version: 2012-10-17
      Statement:
        - Effect: Allow
          Action: s3:*
          Resource:
            - Sub: arn:aws:s3:::${CloudTrailBucket}
            - Sub: arn:aws:s3:::${CloudTrailBucket}/*
          Principal:
            Service: cloudtrail.amazonaws.com

CloudTrail:
  Type: AWS::CloudTrail::Trail
  Properties:
    S3BucketName: Ref: CloudTrailBucket
    IsLogging: true
