Resources:
  ServiceLinkedRole:
    Type: AWS::IAM::ServiceLinkedRole
    Properties:
      AWSServiceName: cloudwatch-crossaccount.amazonaws.com
      Description: Allows CloudWatch to assume CloudWatch-CrossAccountSharing roles in remote accounts on behalf of the current account in order to display data cross-account, cross region

  Fn::Transform:
    Name: AWS::Include
    Properties:
      Location: cloudtrail.template.yml
